name: CI Pipeline
on:
  workflow_dispatch:
#on:
  #push:
    #branches:
      #- main 
   
env:
        DOCKER_IMAGE: surendradev101/petapp:${{ github.sha }}
        MAVEN_OPTS: "-DskipTests=true"      
jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    
  sonar:
      uses: ./.github/workflows/sonar.yml
      needs: build
      secrets: inherit
