# .github/workflows/sonar.yml
name: Sonar Scan

on:
 workflow_call:

jobs:
  sonar:
     runs-on: ubuntu-latest
       steps:
         - name: =sonar scan
          runs-on: java_build
          needs: build
          mvn sonar:sonar \
         -Dsonar.projectKey=demo-org-test_petapp \
         -Dsonar.organization=demo-org-test \
         -Dsonar.host.url=https://sonarcloud.io \
         -Dsonar.login=${{ secrets.SONAR_TOKEN }}
